# Variable
@baseUrl = http://localhost:3000

# Health check
GET {{baseUrl}}/health

###

# Get rooms
GET {{baseUrl}}/rooms

### 

# Create room
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "sala de teste",
  "description": "sala teste"
}